# CPUfreq governors 
obj-$(CONFIG_CPU_FREQ_GOV_PERFORMANCE)	+= cpufreq_performance.o
obj-$(CONFIG_CPU_FREQ_GOV_COMMON)		+= cpufreq_governor.o
obj-$(CONFIG_CPU_FREQ_GOV_FRANKENSTEIN)        	 += cpufreq_frankenstein.o
obj-$(CONFIG_CPU_FREQ_GOV_CONSERVATIVEX)             += cpufreq_conservativex.o
obj-$(CONFIG_CPU_FREQ_GOV_INTEL)             += cpufreq_intel.o
obj-$(CONFIG_CPU_FREQ_GOV_THESSJACTIVE)             += cpufreq_thessjactive.o
obj-$(CONFIG_CPU_FREQ_GOV_ONDEMAND)				+= cpufreq_ondemand.o
